// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using listingApi.data;

namespace listingApi.Migrations
{
    [DbContext(typeof(DatabaseContaxt))]
    [Migration("20210618113400_seedingUpdated")]
    partial class seedingUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("listingApi.data.Country", b =>
                {
                    b.Property<int>("countryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countryId");

                    b.ToTable("Contries");

                    b.HasData(
                        new
                        {
                            countryId = 1,
                            Name = "bhopal",
                            ShortName = "bu"
                        },
                        new
                        {
                            countryId = 2,
                            Name = "indore",
                            ShortName = "in"
                        },
                        new
                        {
                            countryId = 3,
                            Name = "jabalpur mp",
                            ShortName = "ja"
                        },
                        new
                        {
                            countryId = 4,
                            Name = "delhi",
                            ShortName = "da"
                        });
                });

            modelBuilder.Entity("listingApi.data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "mp nager",
                            CountryId = 1,
                            Name = "hotel 1",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "jp nager",
                            CountryId = 2,
                            Name = "hotel 2",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "kp nager",
                            CountryId = 3,
                            Name = "hotel 3",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("listingApi.data.Hotel", b =>
                {
                    b.HasOne("listingApi.data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
